export const chargingStations = [
  {
    id: 1,
    name: "Lulu Mall Charging Hub",
    location: "Edappally, Kochi",
    distance: "2.3 km",
    totalChargers: 8,
    availableChargers: 3,
    connectorTypes: ["CCS2", "AC001", "CHAdeMO"],
    pricePerUnit: 12,
    estimatedWaitTime: 0,
    currentQueue: 0,
    rating: 4.8,
    amenities: ["Parking", "Restroom", "Food Court", "WiFi"],
    coordinates: { lat: 10.0261, lng: 76.3105 },
    operatingHours: "24/7",
    operator: "KSEB",
  },
  {
    id: 2,
    name: "Technopark EV Station",
    location: "Thiruvananthapuram",
    distance: "45.2 km",
    totalChargers: 6,
    availableChargers: 0,
    connectorTypes: ["CCS2", "AC001"],
    pricePerUnit: 10,
    estimatedWaitTime: 25,
    currentQueue: 2,
    rating: 4.6,
    amenities: ["Parking", "WiFi", "Cafe", "Security"],
    coordinates: { lat: 8.5241, lng: 76.9366 },
    operatingHours: "6:00 AM - 10:00 PM",
    operator: "Tata Power",
  },
  {
    id: 3,
    name: "Infopark Charging Point",
    location: "Kakkanad, Kochi",
    distance: "8.7 km",
    totalChargers: 4,
    availableChargers: 2,
    connectorTypes: ["AC001", "Type 2"],
    pricePerUnit: 11,
    estimatedWaitTime: 0,
    currentQueue: 0,
    rating: 4.5,
    amenities: ["Parking", "Security", "Covered Area"],
    coordinates: { lat: 10.0176, lng: 76.3517 },
    operatingHours: "24/7",
    operator: "ChargeZone",
  },
  {
    id: 4,
    name: "Kozhikode Beach Station",
    location: "Kozhikode",
    distance: "195 km",
    totalChargers: 5,
    availableChargers: 1,
    connectorTypes: ["CCS2", "CHAdeMO"],
    pricePerUnit: 13,
    estimatedWaitTime: 15,
    currentQueue: 1,
    rating: 4.7,
    amenities: ["Parking", "Beach View", "Restroom", "Food Stalls"],
    coordinates: { lat: 11.2588, lng: 75.7804 },
    operatingHours: "5:00 AM - 11:00 PM",
    operator: "KSEB",
  },
  {
    id: 5,
    name: "Thrissur Cultural Center",
    location: "Thrissur",
    distance: "58 km",
    totalChargers: 3,
    availableChargers: 3,
    connectorTypes: ["AC001", "Type 2"],
    pricePerUnit: 9,
    estimatedWaitTime: 0,
    currentQueue: 0,
    rating: 4.4,
    amenities: ["Parking", "Cultural Center", "Garden"],
    coordinates: { lat: 10.5276, lng: 76.2144 },
    operatingHours: "6:00 AM - 9:00 PM",
    operator: "Fortum",
  },
]

export const vehicleTypes = [
  { id: "2w", name: "Two Wheeler", icon: "🛵", batteryRange: "5-15 kWh" },
  { id: "3w", name: "Three Wheeler", icon: "🛺", batteryRange: "8-25 kWh" },
  { id: "4w", name: "Four Wheeler", icon: "🚗", batteryRange: "25-100 kWh" },
]

export const connectorInfo = {
  CCS2: { name: "CCS2", power: "50-150 kW", type: "DC Fast" },
  CHAdeMO: { name: "CHAdeMO", power: "50-100 kW", type: "DC Fast" },
  AC001: { name: "AC Type 1", power: "3.3-22 kW", type: "AC Slow" },
  "Type 2": { name: "Type 2", power: "3.3-43 kW", type: "AC Fast" },
}
